### ISSUE TITLE
Notify caller if the Deno process dies?

### ISSUE THREAD

**Issue by tmcw** [casual-simulation/node-deno-vm#22]
Thanks for this great project! I've been trying to use it as a sandbox, and not totally sure with how to handle the whole lifecycle. In particular, if I try to run some code in Deno that uses a forbidden API, like:

```ts
    self.onmessage = (e) => {
      setTimeout(() => {
        self.postMessage(Deno.uid());
      }, 10);
    };
```

This crashes, but I don't know how to know that it crashed. Could there be something like the [exit event that node subprocess provides](https://nodejs.org/api/child_process.html#event-exit), that helps this situation be handled?

**Comment by KallynGowdy** [comment]
This is a good idea. Currently there is no notification when the Deno process exists, but it is a good idea to add a message handler for it.

**Comment by KallynGowdy** [comment]
This feature was added in [v0.8.4](https://www.npmjs.com/package/deno-vm/v/0.8.4).
